-- Обновление изображений для товаров из новой таблицы
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/кач.png' WHERE article = '0110';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/гнездо.png' WHERE article = '0123';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/124 (2).png' WHERE article = '0124';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/128.png' WHERE article = '0125';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/126 (2).png' WHERE article = '0126';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/127 (2).png' WHERE article = '0127';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/125 (2).png' WHERE article = '0128';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/юбюб.png' WHERE article = '0130';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/2.png' WHERE article = '0131';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/карета.png' WHERE article = '0132';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/мишкаа.png' WHERE article = '0133';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/мячикк.png' WHERE article = '0134';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/собачкаа.png' WHERE article = '0135';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/утята.png' WHERE article = '0136';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/якорь.png' WHERE article = '0137';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/буран.png' WHERE article = '0138';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/вихрь.png' WHERE article = '0139';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/0100.png' WHERE article = '0100';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/0100.png' WHERE article = '0100/1';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/0101.png' WHERE article = '0101';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/0101.png' WHERE article = '0101/1';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/0101.png' WHERE article = '0101/2';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/0102.png' WHERE article = '0102';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/0102.png' WHERE article = '0102/1';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/0102.png' WHERE article = '0102/2';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/0103.png' WHERE article = '0103';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/0104.png' WHERE article = '0104';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/105.png' WHERE article = '0105';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/200.png' WHERE article = '0200';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/201.png' WHERE article = '0201';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/202.png' WHERE article = '0202';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/203.png' WHERE article = '0203';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/204.png' WHERE article = '0204';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/205.png' WHERE article = '0205';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/206.png' WHERE article = '0206';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/207.png' WHERE article = '0207';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/208.png' WHERE article = '0208';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/209.png' WHERE article = '0209';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/210.png' WHERE article = '0210';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/211.png' WHERE article = '0211';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/212.png' WHERE article = '0212';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/213.png' WHERE article = '0213';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/214.png' WHERE article = '0214';
UPDATE products SET image_url = 'https://cdn.poehali.dev/files/237.png' WHERE article = '0237';